# Generated by Django 4.1.6 on 2023-08-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Review',
        ),
    ]
